//
//  SettingsRouter.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 2/8/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SettingsRoutingLogic {
    func routeToAboutScene()
    func routeToNotificationsScene()
    func routeToFoodLogScene()
    func routeToParksScene()
    func routeToTermsOfUse()
    func routeToProgramOverview()
    func routeToThirtyDayChallenge()
    func routeToCustomWorkoutScene()
    func routeToExercises()
    func routeToMembership()
}

protocol SettingsDataPassing
{
  var dataStore: SettingsDataStore? { get }
}

class SettingsRouter: NSObject, SettingsRoutingLogic, SettingsDataPassing
{
  weak var viewController: SettingsViewController?
  var dataStore: SettingsDataStore?
  
  // MARK: Routing
    
    func routeToAboutScene() {
        let destination = GenericDetailViewController()
        destination.data = aboutMeData
        navigateTo(source: viewController!, destination: destination)
        
    }
    
    func routeToNotificationsScene() {
        let destination = NotificationsViewController()
        navigateTo(source: viewController!, destination: destination)
    }
    
    func routeToFoodLogScene() {
        let destination = JournalViewController()
        navigateTo(source: viewController!, destination: destination)

    }
    
    func routeToParksScene() {
        let destination = ParksTableViewController()
        navigateTo(source: viewController!, destination: destination)
    }
    
    func routeToTermsOfUse() {
        let destination = GenericDetailViewController()
        destination.data = termsOfUse
        navigateTo(source: viewController!, destination: destination)
    }
    
    func routeToProgramOverview() {
        let destination = GenericDetailViewController()
        destination.data = programOverview
        navigateTo(source: viewController!, destination: destination)
    }
    
    func routeToThirtyDayChallenge() {
        let destination = GenericDetailViewController()
        destination.data = thirtyDayChallenge
        navigateTo(source: viewController!, destination: destination)
    }
    
    func routeToCustomWorkoutScene() {
        let destination = CustomWorkoutViewController()
        navigateTo(source: viewController!, destination: destination)
        
    }
    
    func routeToExercises() {
        let destination = ExerciseViewController()
         navigateTo(source: viewController!, destination: destination)
//        self.exercisesNavVC = UINavigationController(rootViewController: exerciseVC)
//        self.exercisesNavVC.navigationBar.barStyle = .black
//        self.exercisesNavVC.navigationBar.tintColor = .white
//        self.exercisesNavVC.tabBarItem = UITabBarItem(title: "Exercises", image: #imageLiteral(resourceName: "exercises"), selectedImage: nil)
//        self.exercisesNavVC.navigationBar.titleTextAttributes = [.foregroundColor: UIColor.white]
    }
    
    func routeToMembership() {
        // Check if user is premium and route accordingly
        if StoreManager.shared.isPremium {
            // Create and present MembershipDetailView
            let membershipDetailView = MembershipDetailView()
            let hostingController = HostingViewController(view: membershipDetailView)
            navigateTo(source: viewController!, destination: hostingController)
        } else {
            // Present SubscriptionView modally for non-premium users
            let subscriptionView = SubscriptionView { [weak self] success in
                // Handle subscription result
                if success {
                    // Subscription successful, dismiss modal
                    self?.viewController?.dismiss(animated: true)
                }
            }
            let hostingController = HostingViewController(view: subscriptionView)
            hostingController.modalPresentationStyle = .pageSheet
            
            if #available(iOS 15.0, *) {
                if let sheet = hostingController.sheetPresentationController {
                    sheet.detents = [.large()]
                    sheet.prefersGrabberVisible = true
                }
            }
            
            viewController?.present(hostingController, animated: true)
        }
    }

  }

  // MARK: Navigation
  
  func navigateTo(source: SettingsViewController, destination: UIViewController)
  {
    source.show(destination, sender: nil)
  }
  
