//
//  ExercisePresenter.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 5/19/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ExercisePresentationLogic {
  func presentExercises(response: Exercises.Videos.Response)
}

class ExercisePresenter: ExercisePresentationLogic {
  weak var viewController: ExerciseDisplayLogic?
  
  // MARK: Do something
  
  func presentExercises(response: Exercises.Videos.Response)
  {
      let exercisesVM = response.exercises.map( { Exercises.Videos.ViewModel.ExerciseVM(name: $0.name, url: $0.videoURL ?? URL(string: "www.apple.com")!) })
    let viewModel = Exercises.Videos.ViewModel(exerciseViewModel: exercisesVM)
    viewController?.displayExercises(viewModel: viewModel)
  }
}
