//
//  ExerciseViewController.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 5/19/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import AVKit

protocol ExerciseDisplayLogic: AnyObject {
    func displayExercises(viewModel: Exercises.Videos.ViewModel)
}

class ExerciseViewController: UIViewController, ExerciseDisplayLogic
{
    static let videoCellId = "Videos"
    var interactor: (ExerciseBusinessLogic & ExerciseDataStore)?
    var exerciseVM: [Exercises.Videos.ViewModel.ExerciseVM] = []
    private var exerciseLoadingView: ExercisesLoadingView?
    
    // Organized exercise sections
    private var exerciseSections: [(title: String, exercises: [Exercises.Videos.ViewModel.ExerciseVM])] = []
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = ExerciseInteractor()
        let presenter = ExercisePresenter()
        viewController.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = viewController
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        getExercises()
        setUpTableView()
        NotificationCenter.default.addObserver(self, selector: #selector(showWorkoutVC), name: exerciseLoadedNotification, object: nil)
        
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        if exerciseLoadingView == nil {
            if ExerciseStorage.exercises.count <= 0 {
                DispatchQueue.main.async { [weak self] in
                    guard let self = self else { return }
                    self.exerciseLoadingView = ExercisesLoadingView(text: "Available exercises will be here soon!")
                    self.view.addSubview(self.exerciseLoadingView!)
                    self.exerciseLoadingView?.fillSuperview()
                }
            }
        }
    }
    
    // MARK: Do something
    
    @objc private func showWorkoutVC() {
        
        getExercises()
        DispatchQueue.main.async { [weak self] in
            guard let self = self else { return }
            self.exerciseLoadingView?.removeFromSuperview()
            self.exerciseLoadingView = nil
            self.view.setNeedsDisplay()
        }
        
    }
    
    private let tableView = UITableView(frame: .zero, style: .grouped)
    
    private func setUpTableView() {
        view.backgroundColor = .black
        navigationItem.title = "Exercise Library"
        view.addSubview(tableView)
        tableView.fillSuperview()
        tableView.dataSource = self
        tableView.delegate = self
        tableView.backgroundColor = .black
        tableView.separatorStyle = .singleLine
        tableView.separatorColor = UIColor.white.withAlphaComponent(0.2)
        tableView.register(UITableViewCell.self, forCellReuseIdentifier: ExerciseViewController.videoCellId)
    }
    
    func getExercises() {
        let request = Exercises.Videos.Request()
        interactor?.getExercises(request: request)
    }
    
    func displayExercises(viewModel: Exercises.Videos.ViewModel) {
        exerciseVM = viewModel.exerciseViewModel
        organizeExercisesIntoSections()
        tableView.reloadData()
    }
    
    private func organizeExercisesIntoSections() {
        exerciseSections = []
        
        // Define section titles and exercise name patterns
        let sectionDefinitions = [
            ("Core - Beginner", ["plank", "dead bug", "bird dog", "crunches", "wall sit"]),
            ("Core - Novice", ["leg raises", "bicycle crunches", "russian twists", "flutter kicks", "reverse crunches", "side crunches", "oblique crunches", "side plank", "in outs"]),
            ("Core - Solid", ["v-ups", "toe touches", "plank jacks", "t plank", "side plank hipdip", "side plank wrap"]),
            ("Core - Advanced", ["superman", "reverse plank", "open close"]),
            ("Core - Expert", ["pendulums", "kneedrives"]),
            
            ("Upper Body - Beginner", ["wall push ups", "arm circles", "arm swings"]),
            ("Upper Body - Novice", ["push ups", "shoulder rolls", "shoulder shrugs"]),
            ("Upper Body - Solid", ["wide push ups", "pike push ups", "dips"]),
            ("Upper Body - Advanced", ["diamond push ups", "spider push ups"]),
            ("Upper Body - Expert", ["clap push ups"]),
            
            ("Lower Body - Beginner", ["squats", "lunges", "calf raises", "marching in place", "walking in place", "side steps", "standing knee raises"]),
            ("Lower Body - Novice", ["star jumps"]),
            ("Lower Body - Solid", ["jump squats", "squat jumps"]),
            ("Lower Body - Advanced", ["jump lunges", "box jumps"]),
            ("Lower Body - Expert", ["pistol squats"]),
            
            ("Cardio", ["jumping jacks", "high knees", "butt kicks", "mountain climbers", "burpees"]),
            ("Stretching & Recovery", ["neck rolls", "hip circles", "leg swings", "torso twists", "standing forward fold", "side stretches", "quad stretches", "calf stretches", "deep breathing", "wall angels"])
        ]
        
        for (sectionTitle, exerciseNames) in sectionDefinitions {
            let sectionExercises = exerciseVM.filter { exercise in
                exerciseNames.contains { pattern in
                    exercise.name.lowercased().contains(pattern.lowercased())
                }
            }
            
            if !sectionExercises.isEmpty {
                exerciseSections.append((title: sectionTitle, exercises: sectionExercises))
            }
        }
    }
}

extension ExerciseViewController: UITableViewDataSource {
    func numberOfSections(in tableView: UITableView) -> Int {
        return exerciseSections.count
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return exerciseSections[section].exercises.count
    }
    
    func tableView(_ tableView: UITableView, titleForHeaderInSection section: Int) -> String? {
        return exerciseSections[section].title
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let exercise = exerciseSections[indexPath.section].exercises[indexPath.row]
        let cell = tableView.dequeueReusableCell(withIdentifier: ExerciseViewController.videoCellId, for: indexPath) as UITableViewCell
        cell.textLabel?.text = exercise.name.capitalized
        cell.textLabel?.font = UIFont.makeAvenirNext(size: UIDevice.isIpad ? 28 : 18)
        cell.textLabel?.textColor = .white
        cell.backgroundColor = .black
        cell.tintColor = .white
        let image = #imageLiteral(resourceName: "forward").withRenderingMode(.alwaysTemplate)
        let forwardImageView = UIImageView(frame: CGRect(x: 0, y: 0, width: image.size.width, height: image.size.height))
        forwardImageView.image = image
        cell.accessoryView = forwardImageView
        cell.selectionStyle = .none
        return cell
    }
}
extension ExerciseViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let url = exerciseSections[indexPath.section].exercises[indexPath.row].url
        let avPlayerVC = ExercisePlayerViewController()
        avPlayerVC.videoGravity = .resizeAspect
        avPlayerVC.player = AVPlayer(url: url)
        avPlayerVC.player?.isMuted = true
        present(avPlayerVC, animated: true) {
            avPlayerVC.player?.play()
        }
    }
    
    func tableView(_ tableView: UITableView, willDisplayHeaderView view: UIView, forSection section: Int) {
        if let header = view as? UITableViewHeaderFooterView {
            header.textLabel?.textColor = UIColor.goatBlue
            header.textLabel?.font = UIFont.systemFont(ofSize: 16, weight: .semibold)
            header.backgroundView?.backgroundColor = UIColor.black
        }
    }
    
    func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
        return 40
    }
}
